namespace: "ayr_ton"
name: "devstation"
version: "0.0.4"
readme: "README.md"
authors:
  - "DevAllTheThingsOpster <ayrton@linux.com>"
description: "Devstation for AllTheThingsOpsters"
license:
  - "MIT"
tags:
  - linux
  - workstation
  - devops
  - development
  - collection
repository: "https://github.com/ayr-ton/ansible-devstation"
documentation: "https://github.com/ayr-ton/ansible-devstation/blob/main/README.md"
homepage: "https://galaxy.ansible.com/ayr_ton/devstation"
issues: "https://github.com/ayr-ton/ansible-devstation/issues"
