---
# ansible-playbook -i localhost, playbook.yml -e 'ansible_python_interpreter=/usr/bin/python3'

- hosts: all
  connection: local
  gather_facts: yes
  roles:
    - role: common
    - role: dotfiles
    - role: vscode
    - role: docker
