---
# Version to download
visual_studio_code_version: ""

# The url for mirror
visual_studio_code_mirror: "https://packages.microsoft.com"

# Ubuntu only (code-insiders isn't in Microsoft's RPM repo)
visual_studio_code_build: stable

# The package name to install
visual_studio_code_package: "{{ (visual_studio_code_build == 'insiders') | ternary('code-insiders', 'code') }}"

# The CLI executable
visual_studio_code_exe: "{{ (visual_studio_code_build == 'insiders') | ternary('code-insiders', 'code') }}"

