---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:focal
    dockerfile: 'Dockerfile.j2'
    build_image: yes
provisioner:
  name: ansible
verifier:
  name: ansible
