---
- name: Update and upgrade apt packages
  apt:
    upgrade: "yes"
    update_cache: "yes"
    cache_valid_time: 86400 #One day
  become: true

- name: Install common packages
  package:
    name:
      - vim
      - git
      - fonts-powerline
      - fzf
      - zsh
      - direnv
      - exuberant-ctags 
      - ncurses-term
      - curl
      - python3-pip
      - golang
    state: present
  become: yes

- name: Remove unused packages
  package:
    name:
      - nano
    state: absent
  become: yes

- name: Change user shell to zsh
  become: yes
  user:
    name: "{{ current_user }}"
    shell: /usr/bin/zsh
