---
name: CI/CD
'on':
  push:
    branches:
      - main

jobs:
  test-deploy:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install test dependencies
        run: pip3 install ansible molecule[docker] docker yamllint ansible-lint

      - name: Run tests
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
  
      - name: Deploy Ansible Galaxy Collection
        uses: artis3n/ansible_galaxy_collection@v2.6.0
        with:
          api_key: ${{ secrets.API_KEY_TO_THE_GALAXY }}


