---
name: CI
on:
  push:
    branches:
      - main

jobs:
  test:
    name: molecule 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install test dependencies
        run: pip3 install molecule docker yamllint ansible-lint

      - name: Run tests
        run: molecule test